
title: Scott Chamberlain
email: myrmecocystus@gmail.com
host: http://schamberlain.github.com
permalink: pretty
pygments: true
markdown: kramdown

index_pages:
    tag:
        title_prefix:   'Keyword: '

projects:

- title: Mezzanine
  url:   https://github.com/SChamberlain/govdat
  desc:  Interface to APIs for data on what our elected representatives are up to.
  tech:  R
