
title: Scott Chamberlain
email: myrmecocystus@gmail.com
host: http://schamberlain.github.com
permalink: pretty
pygments: true
markdown: kramdown

index_pages:
    tag:
        title_prefix:   'Keyword: '

projects:

- title: govdat
  url:   https://github.com/SChamberlain/govdat
  desc:  Interface to APIs for data on what our elected representatives are up to.
  tech:  R

- title: rgauges
  url:   https://github.com/SChamberlain/rgauges
  desc:  Interface to Gaug.es API.
  tech:  R
  
- title: rplos
  url:   https://github.com/ropensci/rplos
  desc:  Wrapper for the PLoS Journals API.
  tech:  R