url: "http://schamberlain.github.com/"
pygments: true
exclude: [/bin, Gemfile, Gemfile.lock]
markdown: kramdown
permalink: pretty
paginate: 3

kramdown:
  entity_output: symbolic

disqus:
  id: schamber7
