highlighter:      rouge
markdown:         kramdown

gems:         [jekyll-paginate]

title:        Recology
tagline:      'Recology, R/etc.'
description:  'R/etc.'
url:          http://recology.info/
permalink:    /:year/:month/:title/
author:
  name:       'Scott Chamberlain'
  email:      'myrmecocystus@gmail.com'
paginate: 3
