name: Recology
auto: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title/

authors:
  Scott Chamberlain:
    display_name: Scott Chamberlain
    gravatar: d9033fa816e09d79e44995e92f025cdd
    email: myrmecocystus@gmail.com
    web: http://schamberlain.github.com
    twitter: recology_
    github: SChamberlain
  Pascal Mickelson:
    display_name: Pascal Mickelson
    gravatar: 046cbe55c04fa9dee54977c0a1a0ce01
    email: mickelsp@gmail.com
    twitter: mickelsp