# Site settings
title: recology
email: myrmecocystus@gmail.com
description: code and such
permalink:    /:year/:month/:title/
baseurl: ""
url: "https://recology.info"
twitter_username: sckottie
github_username:  sckott
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
# kramdown:
#   syntax_highlighter: rouge
