name: Recology
description: An exploration of using R for ecology, evolution, and open science.
url: http://schamberlain.github.com
paginate: 5
pygments: true
markdown: rdiscount
permalink: /:year/:month/:title/

authors:
  Scott Chamberlain:
    display_name: Scott Chamberlain
    gravatar: d9033fa816e09d79e44995e92f025cdd
    email: myrmecocystus@gmail.com
    web: http://schamberlain.github.com
    twitter: recology_
    github: SChamberlain
  Pascal Mickelson:
    display_name: Pascal Mickelson
    gravatar: 046cbe55c04fa9dee54977c0a1a0ce01
    email: mickelsp@gmail.com
    twitter: mickelsp