title:        Recology
tagline:      'Recology, R ecology'
description:  'R & science'
url:          http://recology.info/
author:
  name:       'Scott Chamberlain'
  email:      'myrmecocystus@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     3