title:        Recology
tagline:      'Recology, R ecology'
description:  'R/etc.'
url:          http://recology.info/
permalink:    /:year/:month/:title/
author:
  name:       'Scott Chamberlain'
  email:      'myrmecocystus@gmail.com'
markdown:     rdiscount
highlighter:  pygments
paginate:     3
